### ISSUE TITLE
Issues with current version of Wordpress

### ISSUE THREAD

**Issue by SharpenedPixels** [elialgranti/geoswitch#5] opened 2015-05-12 12:57 UTC
I'm not sure if this plugin is compatible with the latest version of Wordpress, it doesn't seem to be working for me.

I have tried:

IP OoO [geoswitch_ip] OoO
CITY OoO [geoswitch_city] OoO
STATE OoO [geoswitch_state] OoO
STATE CODE OoO [geoswitch_state_code] OoO
COUNTRY OoO [geoswitch_country] OoO
COUNTRY CODE OoO [geoswitch_country_code] OoO

And this returns my IP address, country and country code. But shortcodes don't seem to be working.

Any help with this would be highly appreciated.

**Comment by elialgranti** [comment] 2015-05-15 13:46
I can reproduce the bug. This seems to be a regression or change of behavior in Wordpress do_shortcode. Will investigate further.

**Comment by SharpenedPixels** [comment] 2015-05-15 13:48
That's great, would be really good if I can get this working on my site. Thanks in advance.

**Comment by elialgranti** [comment] 2015-05-16 10:40
Ok, did some research. The issue is not with do_shortcode as I had initially thought. The issue is actually with the sample code in the read file.
There are two problems with the code:

1. There is an extra space after the closing geoswitch_case tag, i.e it should be [/geoswitch_case] instead of [/geoswitch_case ].
2. The quote characters in the example are not the regular straight quote (") characters but fancy ones (”). This messes up the comparison.

I'll upload an update soon anyway, but would appreciate if you can check whether these are the cause of your issues. If not please post the code that is not working for you.

**Comment by SharpenedPixels** [comment] 2015-05-16 10:49
Ah great, yes i've just tried its working for my location, i'll need to have it checked in another country, but I think that has solved it. If I find it is still displaying the same content in another country I shall inform you. Thanks very much.

**Comment by elialgranti** [comment] 2015-05-18 05:41
I just pushed a new version to wordpress with updated readme and maxmind libraries. I've also added a new configuration setting to override the IP used by the plugin for testing purposes. Wait some time for wordpress.org to update and create the zip files.

**Closed** 2017-06-16 07:12 UTC
